spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE:localhost}:5432/happyAnimal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  servlet:
    context-path: /api