spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/happyAnimal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    serialization:
        write-dates-as-timestamps: true
server:
  servlet:
    context-path: /api
