spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/happyAnimals
    username: postgres
    password: baton1408
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
