spring:
  datasource:
    url: jdbc:postgresql://localhost/happyAnimal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
